services:
  railsapp:
    platform: linux/amd64
    build:
      context: .
      #target: railsapp-prod-no-assets
      #target: railsapp-prod
      target: railsapp-slim
    ports:
      - "3000:3000"
    restart: "no"
